import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {

  const hours = (new Date()).getHours();

  let greeting;

  if (hours >=0 && hours < 11) {
    greeting = 'Good Morning'
  } else if (hours >= 11 && hours < 18) {
    greeting = 'Good Afternoon'
  } else if (hours >= 18 && hours < 21) {
    greeting = 'Good Evening'
  } else {
    greeting = 'Good Night'
  }

  return (
    <>
      <Head>
        <title>Greeting Based on the Time of Day</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <h1>{greeting}</h1>
      </main>
    </>
  );
}
