import { useEffect, useState } from 'react'
import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });


async function getEmojiList() {
  const url = 'https://emojihub.yurace.pro/api/all';

  const response = await fetch(url);
  
  return response.json()
}

// This is a custom hook
// The word 'use' is the prefix for the hook function name via React convention
function useData() {
  const [emojiList, setEmojiList] = useState([])

  useEffect(() => {
    getEmojiList().then(data => {
      const newEmojiList = data.map(item => {
        return {
            name: item.name,
            category: item.category,
            htmlCode: item.htmlCode[0],
        }
      })

      setEmojiList(newEmojiList)
    })
  })

  return emojiList;
}


export default function Home() {

  const emojiList = useData();

  const emojiDisplayList = emojiList.map(
    (item, indexOfArray) => {
      return (
        <li key={indexOfArray}>
          <p>Name: {item.name}</p>
          <p>Category: {item.category}</p>
          <p>Emoji: <span dangerouslySetInnerHTML={{__html: item.htmlCode}}></span></p>
        </li>
      )
    }
  )
  
  return (
    <>
      <Head>
        <title>List out Emojis</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <ul>
          {emojiDisplayList}
        </ul>
      </main>
    </>
  );
}
